apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  type: NodePort
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 3000        # Service port
      targetPort: 3000  # Container port
      nodePort: 30000   # Node port (can be any open port in range 30000–32767)
